id: I12FDFBDB
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T19:08:29.910109'
last_modified: '2022-05-27T19:08:29.910121'
parser: null
source_metadata:
  title: Saṅghabhedavastu
  language: zh
  base:
    f868E:
      title: Title
      base_file: f868E.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
